<template>
  <div>
    <div class="mb-5 flex items-end justify-between gap-4 flex-wrap">
      <div><div class="flex items-center gap-2 text-xs text-slate-400 mb-1.5"><router-link :to="{ name: 'admin-dashboard' }" class="hover:text-brand-600">Tổng quan</router-link><i class="fa-solid fa-chevron-right text-[9px]"></i><span class="text-slate-600">Báo cáo</span></div><h1 class="text-2xl font-bold text-slate-900">Báo cáo & Thống kê</h1></div>
      <div class="flex items-center gap-2"><select v-model="lopChon" class="o-nhap !w-auto min-w-[220px]" @change="xemBaoCao"><option value="">Chọn lớp học phần</option><option v-for="l in lops" :key="l.id" :value="l.id">{{ l.ma_lop_hoc }} – {{ l.ten_lop }}</option></select><a v-if="lopChon" :href="urlXuatDiemDanh" target="_blank" class="nut-phu text-sm"><i class="fa-solid fa-download"></i>Xuất báo cáo</a></div>
    </div>

    <div class="flex gap-1 border-b border-slate-200 mb-6 overflow-x-auto"><button v-for="tab in tabs" :key="tab.k" class="flex items-center gap-2 px-4 py-3 text-sm font-medium border-b-2 transition-colors whitespace-nowrap" :class="reportTab === tab.k ? 'text-brand-600 border-brand-600' : 'text-slate-500 border-transparent hover:text-slate-700'" @click="reportTab = tab.k"><i :class="tab.icon" class="text-xs"></i>{{ tab.ten }}</button></div>

    <div v-if="reportTab === 'overview'" class="space-y-5">
      <div class="grid grid-cols-2 lg:grid-cols-4 gap-4"><div v-for="th in thongKeTongQuan" :key="th.nhan" class="the p-5 flex items-start gap-4"><div class="w-11 h-11 rounded-xl flex items-center justify-center shrink-0" :class="th.nen"><i :class="th.icon"></i></div><div><p class="text-xs text-slate-500 font-medium">{{ th.nhan }}</p><p class="text-2xl font-bold text-slate-900 mt-0.5">{{ th.giaTri }}</p><p v-if="th.phu" class="text-xs text-slate-500 mt-0.5">{{ th.phu }}</p></div></div></div>
      <div class="the overflow-hidden"><div class="px-5 py-4 border-b border-slate-100 bg-slate-50"><h3 class="font-semibold text-slate-900 text-sm">Thống kê lớp học phần</h3></div><div class="overflow-x-auto"><table class="bang"><thead><tr><th>Mã lớp</th><th>Lớp học phần</th><th>Học kỳ</th><th>Sinh viên</th><th>Trạng thái</th></tr></thead><tbody><tr v-for="l in lops" :key="l.id"><td class="font-mono text-xs font-bold text-brand-600">{{ l.ma_lop_hoc }}</td><td class="font-semibold text-slate-800">{{ l.ten_lop }}</td><td>{{ l.hoc_ky }} {{ l.nam_hoc }}</td><td>{{ l.so_sinh_vien || 0 }}/{{ l.so_luong_toi_da }}</td><td><span class="nhan border" :class="mauTrangThaiLop(l.trang_thai)">{{ tenTrangThaiLop(l.trang_thai) }}</span></td></tr></tbody></table></div></div>
    </div>

    <div v-if="reportTab === 'attendance'" class="space-y-5">
      <div class="grid grid-cols-2 sm:grid-cols-4 gap-4"><div v-for="th in thongKeChuyenCan" :key="th.nhan" class="the p-5 flex items-start gap-4"><div class="w-11 h-11 rounded-xl flex items-center justify-center shrink-0" :class="th.nen"><i :class="th.icon"></i></div><div><p class="text-xs text-slate-500 font-medium">{{ th.nhan }}</p><p class="text-2xl font-bold text-slate-900 mt-0.5">{{ th.giaTri }}</p></div></div></div>
      <div v-if="!lopChon" class="the p-12 text-center text-slate-400"><i class="fa-solid fa-clipboard-check text-3xl text-slate-200 block mb-2"></i>Chọn lớp học phần để xem báo cáo chuyên cần.</div>
      <div v-else-if="baoCao" class="the overflow-hidden"><div class="px-5 py-4 border-b border-slate-100 flex items-center justify-between"><div><h3 class="font-semibold text-slate-900 text-sm">Báo cáo điểm danh {{ baoCao.lop_hoc.ten_lop }}</h3><p class="text-xs text-slate-500 mt-0.5">{{ baoCao.so_phien_diem_danh }} phiên đã đóng</p></div><a :href="urlXuatDiemDanh" target="_blank" class="nut-phu text-xs"><i class="fa-solid fa-file-excel text-emerald-600"></i>Xuất Excel</a></div><div class="overflow-x-auto"><table class="bang"><thead><tr><th>Mã SV</th><th>Họ tên</th><th class="!text-center">Số buổi</th><th class="!text-center">Có mặt</th><th class="!text-center">Vắng</th><th class="!text-center">Xin phép</th><th style="min-width:180px">Tỷ lệ chuyên cần</th></tr></thead><tbody><tr v-for="d in baoCao.danh_sach" :key="d.ma_sv_text"><td class="font-mono text-xs font-semibold">{{ d.ma_sv_text }}</td><td class="font-medium text-slate-800">{{ d.ho_ten }}</td><td class="!text-center">{{ d.so_buoi }}</td><td class="!text-center font-bold text-emerald-600">{{ d.so_co_mat }}</td><td class="!text-center font-bold text-rose-600">{{ d.so_vang }}</td><td class="!text-center">{{ d.so_xin_phep }}</td><td><div class="flex items-center gap-2"><div class="flex-1 h-2 rounded-full bg-slate-100 overflow-hidden"><div class="h-full rounded-full" :class="d.ty_le_chuyen_can >= 80 ? 'bg-emerald-500' : d.ty_le_chuyen_can >= 50 ? 'bg-amber-500' : 'bg-rose-500'" :style="{ width: d.ty_le_chuyen_can + '%' }"></div></div><span class="text-xs font-bold text-slate-600">{{ d.ty_le_chuyen_can }}%</span></div></td></tr><tr v-if="!baoCao.danh_sach.length"><td colspan="7" class="!py-12 text-center text-slate-400">Lớp chưa có sinh viên.</td></tr></tbody></table></div></div>
    </div>

    <div v-if="reportTab === 'grades'" class="space-y-5"><div class="grid grid-cols-2 sm:grid-cols-4 gap-4"><div v-for="th in thongKeDiem" :key="th.nhan" class="the p-5 flex items-start gap-4"><div class="w-11 h-11 rounded-xl flex items-center justify-center shrink-0" :class="th.nen"><i :class="th.icon"></i></div><div><p class="text-xs text-slate-500 font-medium">{{ th.nhan }}</p><p class="text-2xl font-bold text-slate-900 mt-0.5">{{ th.giaTri }}</p></div></div></div><div class="the p-8 text-center"><div class="w-14 h-14 bg-amber-50 text-amber-600 rounded-2xl flex items-center justify-center mx-auto mb-3"><i class="fa-solid fa-star text-xl"></i></div><h3 class="font-semibold text-slate-900">Báo cáo điểm số theo lớp</h3><p class="text-sm text-slate-500 mt-1 mb-4">Chọn lớp học phần rồi xuất bảng điểm đầy đủ.</p><a v-if="lopChon" :href="urlXuatDiem" target="_blank" class="nut-chinh inline-flex"><i class="fa-solid fa-file-excel"></i>Xuất bảng điểm</a></div></div>

    <div v-if="reportTab === 'courses'" class="space-y-5"><div class="grid grid-cols-2 sm:grid-cols-4 gap-4"><div v-for="th in thongKeHocPhan" :key="th.nhan" class="the p-5 flex items-start gap-4"><div class="w-11 h-11 rounded-xl flex items-center justify-center shrink-0" :class="th.nen"><i :class="th.icon"></i></div><div><p class="text-xs text-slate-500 font-medium">{{ th.nhan }}</p><p class="text-2xl font-bold text-slate-900 mt-0.5">{{ th.giaTri }}</p></div></div></div><div class="the overflow-hidden"><div class="px-5 py-4 border-b border-slate-100 bg-slate-50"><h3 class="font-semibold text-slate-900 text-sm">Mức độ đăng ký lớp học phần</h3></div><div class="divide-y divide-slate-50"><div v-for="(l, i) in lopTheoDangKy" :key="l.id" class="flex items-center gap-4 px-5 py-3.5"><div class="w-8 h-8 rounded-xl flex items-center justify-center text-sm font-bold shrink-0" :class="i < 3 ? 'bg-amber-100 text-amber-700' : 'bg-slate-50 text-slate-500'">{{ i + 1 }}</div><div class="flex-1 min-w-0"><p class="text-sm font-semibold text-slate-800">{{ l.ten_lop }} <span class="text-xs font-mono text-slate-400">{{ l.ma_lop_hoc }}</span></p><p class="text-xs text-slate-500">{{ l.hoc_ky }} {{ l.nam_hoc }}</p></div><div class="text-right shrink-0"><p class="text-sm font-bold text-brand-600">{{ l.so_sinh_vien || 0 }}</p><p class="text-xs text-slate-400">sinh viên</p></div><div class="w-24 shrink-0"><div class="h-1.5 bg-slate-100 rounded-full overflow-hidden"><div class="h-full bg-emerald-500 rounded-full" :style="{ width: tyLeLapDay(l) + '%' }"></div></div><p class="text-xs text-slate-400 text-right mt-1">{{ tyLeLapDay(l) }}%</p></div></div></div></div></div>
  </div>
</template>

<script>
import api from '../../utils/axios'

export default {
  name: 'admin-bao-cao',
  data() { return { lops: [], lopChon: '', baoCao: null, reportTab: 'overview', tabs: [
    { k: 'overview', ten: 'Tổng quan', icon: 'fa-solid fa-chart-pie' }, { k: 'attendance', ten: 'Chuyên cần', icon: 'fa-solid fa-clipboard-check' }, { k: 'grades', ten: 'Điểm số', icon: 'fa-solid fa-star' }, { k: 'courses', ten: 'Học phần', icon: 'fa-solid fa-book' },
  ] } },
  computed: {
    baseURL() { return api.defaults.baseURL },
    urlXuatDiemDanh() { return `${this.baseURL}admin/bao-cao/diem-danh/${this.lopChon}/xuat?token=${localStorage.getItem('token')}` },
    urlXuatDiem() { return `${this.baseURL}admin/bao-cao/diem/${this.lopChon}/xuat?token=${localStorage.getItem('token')}` },
    tongSinhVien() { return this.lops.reduce((s, l) => s + Number(l.so_sinh_vien || 0), 0) },
    tyLeChuyenCanTB() { if (!this.baoCao?.danh_sach?.length) return '—'; return `${Math.round(this.baoCao.danh_sach.reduce((s, d) => s + Number(d.ty_le_chuyen_can || 0), 0) / this.baoCao.danh_sach.length)}%` },
    thongKeTongQuan() { return [
      { icon: 'fa-solid fa-users', nen: 'bg-indigo-50 text-indigo-600', nhan: 'Tổng lượt sinh viên', giaTri: this.tongSinhVien }, { icon: 'fa-solid fa-chalkboard', nen: 'bg-teal-50 text-teal-600', nhan: 'Lớp học phần', giaTri: this.lops.length }, { icon: 'fa-solid fa-percent', nen: 'bg-emerald-50 text-emerald-600', nhan: 'Chuyên cần TB', giaTri: this.tyLeChuyenCanTB, phu: this.lopChon ? 'Lớp đang chọn' : 'Chọn lớp để tính' }, { icon: 'fa-solid fa-circle-play', nen: 'bg-amber-50 text-amber-600', nhan: 'Đang hoạt động', giaTri: this.lops.filter((l) => l.trang_thai === 'dang_hoc').length },
    ] },
    thongKeChuyenCan() { const ds = this.baoCao?.danh_sach || []; return [
      { icon: 'fa-solid fa-percent', nen: 'bg-emerald-50 text-emerald-600', nhan: 'Chuyên cần TB', giaTri: this.tyLeChuyenCanTB }, { icon: 'fa-solid fa-user-check', nen: 'bg-indigo-50 text-indigo-600', nhan: 'SV đạt ≥ 80%', giaTri: ds.filter((d) => d.ty_le_chuyen_can >= 80).length }, { icon: 'fa-solid fa-user-xmark', nen: 'bg-rose-50 text-rose-600', nhan: 'SV dưới 80%', giaTri: ds.filter((d) => d.ty_le_chuyen_can < 80).length }, { icon: 'fa-solid fa-calendar-xmark', nen: 'bg-amber-50 text-amber-600', nhan: 'Tổng buổi vắng', giaTri: ds.reduce((s, d) => s + Number(d.so_vang || 0), 0) },
    ] },
    thongKeDiem() { return [ { icon: 'fa-solid fa-star', nen: 'bg-amber-50 text-amber-600', nhan: 'Lớp đã chọn', giaTri: this.lopChon ? 1 : 0 }, { icon: 'fa-solid fa-graduation-cap', nen: 'bg-indigo-50 text-indigo-600', nhan: 'Sinh viên', giaTri: this.baoCao?.danh_sach?.length || 0 }, { icon: 'fa-solid fa-book-open', nen: 'bg-teal-50 text-teal-600', nhan: 'Lớp học phần', giaTri: this.lops.length }, { icon: 'fa-solid fa-file-export', nen: 'bg-violet-50 text-violet-600', nhan: 'Định dạng xuất', giaTri: 'XLSX' } ] },
    thongKeHocPhan() { return [ { icon: 'fa-solid fa-book', nen: 'bg-indigo-50 text-indigo-600', nhan: 'Lớp học phần', giaTri: this.lops.length }, { icon: 'fa-solid fa-circle-play', nen: 'bg-emerald-50 text-emerald-600', nhan: 'Đang hoạt động', giaTri: this.lops.filter((l) => l.trang_thai === 'dang_hoc').length }, { icon: 'fa-solid fa-calendar-plus', nen: 'bg-blue-50 text-blue-600', nhan: 'Mở đăng ký', giaTri: this.lops.filter((l) => l.trang_thai === 'mo_dang_ky').length }, { icon: 'fa-solid fa-users', nen: 'bg-violet-50 text-violet-600', nhan: 'Lượt đăng ký', giaTri: this.tongSinhVien } ] },
    lopTheoDangKy() { return [...this.lops].sort((a, b) => Number(b.so_sinh_vien || 0) - Number(a.so_sinh_vien || 0)).slice(0, 8) },
  },
  async created() { const { data } = await api.get('/admin/lop-hoc'); this.lops = data.danh_sach || [] },
  methods: {
    async xemBaoCao() { this.baoCao = null; if (!this.lopChon) return; const { data } = await api.get(`/admin/bao-cao/diem-danh/${this.lopChon}`); this.baoCao = data },
    tyLeLapDay(l) { return l.so_luong_toi_da ? Math.min(100, Math.round(Number(l.so_sinh_vien || 0) / Number(l.so_luong_toi_da) * 100)) : 0 },
    tenTrangThaiLop(t) { return { mo_dang_ky: 'Mở đăng ký', dang_hoc: 'Đang học', da_ket_thuc: 'Đã kết thúc' }[t] || t },
    mauTrangThaiLop(t) { return { mo_dang_ky: 'bg-blue-50 text-blue-700 border-blue-200', dang_hoc: 'bg-emerald-50 text-emerald-700 border-emerald-200', da_ket_thuc: 'bg-slate-100 text-slate-600 border-slate-200' }[t] || 'bg-slate-100 text-slate-600 border-slate-200' },
  },
}
</script>
